<wsdl:definitions
     name="ForexSync_DEV"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ForexSync/ForexSync/ForexSync_DEV"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ForexSync/ForexSync/ForexSync_DEV"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ForexSync_DEV"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="ForexSync_DEV_plt" >
    <plt:role name="ForexSync_DEV_role" >
      <plt:portType name="tns:ForexSync_DEV_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ForexSync_DEV" schemaLocation="ForexSync_DEV_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="ForexrateCollection_msg">
        <wsdl:part name="ForexrateCollection" element="top:ForexrateCollection"/>
    </wsdl:message>
    <wsdl:portType name="ForexSync_DEV_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:ForexrateCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
